# -*- coding: utf-8 -*-
"""Skripsi - Evaluasi per Tipe Entitas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12uB_QhJ3I8PoduwJIA9ttCa2W_p6QbWH
"""

# 1. Install library yang dibutuhkan (Run ini jika di Google Colab)
!pip install fuzzywuzzy python-Levenshtein

import pandas as pd
import re
from fuzzywuzzy import fuzz

import pandas as pd
import re
from fuzzywuzzy import fuzz

# ==========================================
# 2. CONFIGURATION & LOAD DATA
# ==========================================
PREDICTION_FILE = "gpt5_(1).csv"
GROUND_TRUTH_FILE = "Ground Truth - Ground Truth.csv"

df_preds = pd.read_csv(PREDICTION_FILE)
df_gold = pd.read_csv(GROUND_TRUTH_FILE)

df_preds.columns = df_preds.columns.str.strip()
df_gold.columns = df_gold.columns.str.strip()

# ==========================================
# 3. FUNGSI EVALUASI (Per Tipe Entitas)
# ==========================================

def normalize_text(text):
    if pd.isna(text): return ""
    text = str(text).lower()
    text = text.replace("##", "") # Antisipasi sisa sub-word
    text = re.sub(r"[^\w\s]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

def exact_match(pred_entities, gold_entities):
    # Set-based evaluation
    pred_set = {(normalize_text(e["text"]), e["type"]) for e in pred_entities}
    gold_set = {(normalize_text(g["text"]), g["type"]) for g in gold_entities}

    tp = len(pred_set & gold_set)
    fp = len(pred_set - gold_set)
    fn = len(gold_set - pred_set)
    return tp, fp, fn

def relaxed_match(pred_entities, gold_entities):
    tp = 0
    used_gold = set()
    for p in pred_entities:
        p_tokens = set(normalize_text(p["text"]).split())
        if not p_tokens: continue

        for i, g in enumerate(gold_entities):
            if i in used_gold: continue
            g_tokens = set(normalize_text(g["text"]).split())

            # Jika tipe sama dan ada overlap token
            if p["type"] == g["type"] and (p_tokens & g_tokens):
                tp += 1
                used_gold.add(i)
                break

    fp = len(pred_entities) - tp
    fn = len(gold_entities) - tp
    return tp, fp, fn

def fuzzy_match(pred_entities, gold_entities, threshold=60):
    tp = 0
    used_gold = set()
    for p in pred_entities:
        for i, g in enumerate(gold_entities):
            if i in used_gold or p["type"] != g["type"]: continue

            score = fuzz.token_set_ratio(normalize_text(p["text"]), normalize_text(g["text"]))
            if score >= threshold:
                tp += 1
                used_gold.add(i)
                break

    fp = len(pred_entities) - tp
    fn = len(gold_entities) - tp
    return tp, fp, fn

def compute_prf(tp, fp, fn):
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0
    f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0
    return precision, recall, f1

# List semua tipe entitas unik dari Ground Truth
entity_types = sorted(df_gold["entity_type"].unique().tolist())

# Inisialisasi struktur metrics: { mode: { type: [tp, fp, fn] } }
detailed_metrics = {
    mode: {etype: [0, 0, 0] for etype in entity_types}
    for mode in ["exact", "relaxed", "fuzzy"]
}

# Proses per artikel
articles = df_gold["article_id"].unique()

for article_id in articles:
    # 1. Ambil Prediksi
    pred_data = df_preds[df_preds["article_id"] == article_id]

    # 2. Ambil Ground Truth
    gold_data = df_gold[df_gold["article_id"] == article_id]

    for etype in entity_types:
        # Filter entitas berdasarkan tipe saat ini
        p_entities = [{"text": r["entity"], "type": r["entity_type"]}
                      for _, r in pred_data[pred_data["entity_type"] == etype].iterrows()]

        g_entities = [{"text": r["entity"], "type": r["entity_type"]}
                      for _, r in gold_data[gold_data["entity_type"] == etype].iterrows()]

        # Hitung TP, FP, FN untuk tipe ini
        for mode, func in [("exact", exact_match), ("relaxed", relaxed_match), ("fuzzy", fuzzy_match)]:
            tp, fp, fn = func(p_entities, g_entities)
            detailed_metrics[mode][etype][0] += tp
            detailed_metrics[mode][etype][1] += fp
            detailed_metrics[mode][etype][2] += fn

# ==========================================
# 4. REKAPITULASI, DISPLAY, & SIMPAN KE CSV
# ==========================================

# List untuk menampung semua hasil agar bisa digabung jika perlu
all_results = []

for mode in ["exact", "relaxed", "fuzzy"]:
    print(f"\n--- Evaluation Report: {mode.upper()} MATCHING ---")
    mode_results = []

    for etype in entity_types:
        tp, fp, fn = detailed_metrics[mode][etype]
        p, r, f1 = compute_prf(tp, fp, fn)

        row = {
            "Method": mode.capitalize(),
            "Entity Type": etype,
            "Precision": round(p, 4),
            "Recall": round(r, 4),
            "F1-Score": round(f1, 4),
            "TP": tp,
            "FP": fp,
            "FN": fn
        }
        mode_results.append(row)
        all_results.append(row)

    # 1. Tampilkan tabel di terminal/console
    df_mode_report = pd.DataFrame(mode_results)
    print(df_mode_report.to_string(index=False))

# ==========================================
# 5. SIMPAN SEMUA HASIL KE SATU FILE CSV
# ==========================================
final_csv_name = "hasil_evaluasi_per_label_lengkap.csv"
df_final = pd.DataFrame(all_results)

# Simpan ke CSV
df_final.to_csv(final_csv_name, index=False)

print(f"\n" + "="*40)
print(f"SUKSES: Seluruh hasil evaluasi per label telah disimpan ke file: {final_csv_name}")
print("="*40)