# -*- coding: utf-8 -*-
"""Skripsi-GPT Evaluasi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TJiuwKv_F2h55cUlGgkt8Ujy0iOmxqhY

# Evaluasi Hasil NER dari Model GPT
"""

# 1. Install library yang dibutuhkan (Run ini jika di Google Colab)
!pip install fuzzywuzzy python-Levenshtein

import pandas as pd
import re
from fuzzywuzzy import fuzz

"""
---

(1)"""

# ==========================================
# 2. CONFIGURATION & LOAD DATA
# ==========================================
# Ganti nama file jika berbeda
PREDICTION_FILE = "gpt4o_(1).csv"
GROUND_TRUTH_FILE = "Ground Truth - Ground Truth.csv"

# Load Data
df_preds = pd.read_csv(PREDICTION_FILE)
df_gold = pd.read_csv(GROUND_TRUTH_FILE)

# Bersihkan spasi di nama kolom
df_preds.columns = df_preds.columns.str.strip()
df_gold.columns = df_gold.columns.str.strip()

# ==========================================
# 3. FUNGSI EVALUASI (Sesuai Logika BERT)
# ==========================================
def normalize_text(text):
    if pd.isna(text): return ""
    text = str(text).lower()
    text = text.replace("##", "") # Antisipasi sisa sub-word
    text = re.sub(r"[^\w\s]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

def exact_match(pred_entities, gold_entities):
    # Set-based evaluation
    pred_set = {(normalize_text(e["text"]), e["type"]) for e in pred_entities}
    gold_set = {(normalize_text(g["text"]), g["type"]) for g in gold_entities}

    tp = len(pred_set & gold_set)
    fp = len(pred_set - gold_set)
    fn = len(gold_set - pred_set)
    return tp, fp, fn

def relaxed_match(pred_entities, gold_entities):
    tp = 0
    used_gold = set()
    for p in pred_entities:
        p_tokens = set(normalize_text(p["text"]).split())
        if not p_tokens: continue

        for i, g in enumerate(gold_entities):
            if i in used_gold: continue
            g_tokens = set(normalize_text(g["text"]).split())

            # Jika tipe sama dan ada overlap token
            if p["type"] == g["type"] and (p_tokens & g_tokens):
                tp += 1
                used_gold.add(i)
                break

    fp = len(pred_entities) - tp
    fn = len(gold_entities) - tp
    return tp, fp, fn

def fuzzy_match(pred_entities, gold_entities, threshold=60):
    tp = 0
    used_gold = set()
    for p in pred_entities:
        for i, g in enumerate(gold_entities):
            if i in used_gold or p["type"] != g["type"]: continue

            score = fuzz.token_set_ratio(normalize_text(p["text"]), normalize_text(g["text"]))
            if score >= threshold:
                tp += 1
                used_gold.add(i)
                break

    fp = len(pred_entities) - tp
    fn = len(gold_entities) - tp
    return tp, fp, fn

def compute_prf(tp, fp, fn):
    precision = tp / (tp + fp) if tp + fp > 0 else 0
    recall = tp / (tp + fn) if tp + fn > 0 else 0
    f1 = (2 * precision * recall / (precision + recall)) if precision + recall > 0 else 0
    return precision, recall, f1

# ==========================================
# 4. PROSES EVALUASI
# ==========================================
def run_evaluation():
    # Ambil daftar unik article_id yang ada di Ground Truth
    list_article_id = df_gold['article_id'].unique()

    overall_metrics = {"exact": [0,0,0], "relaxed": [0,0,0], "fuzzy": [0,0,0]}

    print(f"Memulai evaluasi pada {len(list_article_id)} artikel...")

    for article_id in list_article_id:
        # 1. Ambil Prediksi GPT-4o untuk artikel ini
        pred_data = df_preds[df_preds["article_id"] == article_id]

        pred_entities = []
        seen_preds = set()

        for _, r in pred_data.iterrows():
            clean_text = str(r["entity"]).strip()
            clean_type = str(r["entity_type"]).strip()

            # Logika Unikalisasi (Identik dengan script BERT)
            identifier = (normalize_text(clean_text), clean_type)
            if identifier not in seen_preds and len(clean_text) > 1:
                pred_entities.append({"text": clean_text, "type": clean_type})
                seen_preds.add(identifier)

        # 2. Ambil Ground Truth untuk artikel ini
        gold_data = df_gold[df_gold["article_id"] == article_id]
        gold_entities = [{"text": r["entity"], "type": r["entity_type"]} for _, r in gold_data.iterrows()]

        # 3. Hitung TP, FP, FN per metode
        for mode, func in [("exact", exact_match), ("relaxed", relaxed_match), ("fuzzy", fuzzy_match)]:
            tp, fp, fn = func(pred_entities, gold_entities)
            overall_metrics[mode][0] += tp
            overall_metrics[mode][1] += fp
            overall_metrics[mode][2] += fn

    # 4. Rekapitulasi Hasil Akhir (Micro Average)
    final_report = []
    for mode in ["exact", "relaxed", "fuzzy"]:
        tp, fp, fn = overall_metrics[mode]
        p, r, f1 = compute_prf(tp, fp, fn)
        final_report.append({
            "Method": mode.capitalize(),
            "Precision": round(p, 4),
            "Recall": round(r, 4),
            "F1-Score": round(f1, 4),
            "TP": tp,
            "FP": fp,
            "FN": fn
        })

    df_report = pd.DataFrame(final_report)
    print("\n" + "="*50)
    print("HASIL EVALUASI GPT-4o (MICRO AVERAGE)")
    print("="*50)
    print(df_report)

if __name__ == "__main__":
    run_evaluation()

"""
---

(2)"""

# ==========================================
# 2. CONFIGURATION & LOAD DATA
# ==========================================
# Ganti nama file jika berbeda
PREDICTION_FILE = "gpt4o_(2).csv"
GROUND_TRUTH_FILE = "Ground Truth - Ground Truth.csv"

# Load Data
df_preds = pd.read_csv(PREDICTION_FILE)
df_gold = pd.read_csv(GROUND_TRUTH_FILE)

# Bersihkan spasi di nama kolom
df_preds.columns = df_preds.columns.str.strip()
df_gold.columns = df_gold.columns.str.strip()

# ==========================================
# 3. FUNGSI EVALUASI (Sesuai Logika BERT)
# ==========================================
def normalize_text(text):
    if pd.isna(text): return ""
    text = str(text).lower()
    text = text.replace("##", "") # Antisipasi sisa sub-word
    text = re.sub(r"[^\w\s]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

def exact_match(pred_entities, gold_entities):
    # Set-based evaluation
    pred_set = {(normalize_text(e["text"]), e["type"]) for e in pred_entities}
    gold_set = {(normalize_text(g["text"]), g["type"]) for g in gold_entities}

    tp = len(pred_set & gold_set)
    fp = len(pred_set - gold_set)
    fn = len(gold_set - pred_set)
    return tp, fp, fn

def relaxed_match(pred_entities, gold_entities):
    tp = 0
    used_gold = set()
    # Meniru logika iteratif dari script BERT
    for p in pred_entities:
        p_tokens = set(normalize_text(p["text"]).split())
        if not p_tokens: continue

        for i, g in enumerate(gold_entities):
            if i in used_gold: continue
            g_tokens = set(normalize_text(g["text"]).split())

            # Jika tipe sama dan ada overlap token
            if p["type"] == g["type"] and (p_tokens & g_tokens):
                tp += 1
                used_gold.add(i)
                break

    fp = len(pred_entities) - tp
    fn = len(gold_entities) - tp
    return tp, fp, fn

def fuzzy_match(pred_entities, gold_entities, threshold=60):
    tp = 0
    used_gold = set()
    for p in pred_entities:
        for i, g in enumerate(gold_entities):
            if i in used_gold or p["type"] != g["type"]: continue

            score = fuzz.token_set_ratio(normalize_text(p["text"]), normalize_text(g["text"]))
            if score >= threshold:
                tp += 1
                used_gold.add(i)
                break

    fp = len(pred_entities) - tp
    fn = len(gold_entities) - tp
    return tp, fp, fn

def compute_prf(tp, fp, fn):
    precision = tp / (tp + fp) if tp + fp > 0 else 0
    recall = tp / (tp + fn) if tp + fn > 0 else 0
    f1 = (2 * precision * recall / (precision + recall)) if precision + recall > 0 else 0
    return precision, recall, f1

# ==========================================
# 4. PROSES EVALUASI
# ==========================================
def run_evaluation():
    # Ambil daftar unik article_id yang ada di Ground Truth
    list_article_id = df_gold['article_id'].unique()

    overall_metrics = {"exact": [0,0,0], "relaxed": [0,0,0], "fuzzy": [0,0,0]}

    print(f"Memulai evaluasi pada {len(list_article_id)} artikel...")

    for article_id in list_article_id:
        # 1. Ambil Prediksi GPT-4o untuk artikel ini
        pred_data = df_preds[df_preds["article_id"] == article_id]

        pred_entities = []
        seen_preds = set()

        for _, r in pred_data.iterrows():
            clean_text = str(r["entity"]).strip()
            clean_type = str(r["entity_type"]).strip()

            # Logika Unikalisasi (Identik dengan script BERT)
            identifier = (normalize_text(clean_text), clean_type)
            if identifier not in seen_preds and len(clean_text) > 1:
                pred_entities.append({"text": clean_text, "type": clean_type})
                seen_preds.add(identifier)

        # 2. Ambil Ground Truth untuk artikel ini
        gold_data = df_gold[df_gold["article_id"] == article_id]
        gold_entities = [{"text": r["entity"], "type": r["entity_type"]} for _, r in gold_data.iterrows()]

        # 3. Hitung TP, FP, FN per metode
        for mode, func in [("exact", exact_match), ("relaxed", relaxed_match), ("fuzzy", fuzzy_match)]:
            tp, fp, fn = func(pred_entities, gold_entities)
            overall_metrics[mode][0] += tp
            overall_metrics[mode][1] += fp
            overall_metrics[mode][2] += fn

    # 4. Rekapitulasi Hasil Akhir (Micro Average)
    final_report = []
    for mode in ["exact", "relaxed", "fuzzy"]:
        tp, fp, fn = overall_metrics[mode]
        p, r, f1 = compute_prf(tp, fp, fn)
        final_report.append({
            "Method": mode.capitalize(),
            "Precision": round(p, 4),
            "Recall": round(r, 4),
            "F1-Score": round(f1, 4),
            "TP": tp,
            "FP": fp,
            "FN": fn
        })

    df_report = pd.DataFrame(final_report)
    print("\n" + "="*50)
    print("HASIL EVALUASI GPT-4o (MICRO AVERAGE)")
    print("="*50)
    print(df_report)

if __name__ == "__main__":
    run_evaluation()

"""---

(3)

1-Shot Prompting
"""

# ==========================================
# 2. CONFIGURATION & LOAD DATA
# ==========================================
# Ganti nama file jika berbeda
PREDICTION_FILE = "gpt5_(3)_One-Shot.csv"
GROUND_TRUTH_FILE = "GroundTruth_1Shot.csv"

# Load Data
df_preds = pd.read_csv(PREDICTION_FILE)
df_gold = pd.read_csv(GROUND_TRUTH_FILE)

# Bersihkan spasi di nama kolom
df_preds.columns = df_preds.columns.str.strip()
df_gold.columns = df_gold.columns.str.strip()

# ==========================================
# 3. FUNGSI EVALUASI (Sesuai Logika BERT)
# ==========================================
def normalize_text(text):
    if pd.isna(text): return ""
    text = str(text).lower()
    text = text.replace("##", "") # Antisipasi sisa sub-word
    text = re.sub(r"[^\w\s]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

def exact_match(pred_entities, gold_entities):
    # Set-based evaluation
    pred_set = {(normalize_text(e["text"]), e["type"]) for e in pred_entities}
    gold_set = {(normalize_text(g["text"]), g["type"]) for g in gold_entities}

    tp = len(pred_set & gold_set)
    fp = len(pred_set - gold_set)
    fn = len(gold_set - pred_set)
    return tp, fp, fn

def relaxed_match(pred_entities, gold_entities):
    tp = 0
    used_gold = set()
    # Meniru logika iteratif dari script BERT
    for p in pred_entities:
        p_tokens = set(normalize_text(p["text"]).split())
        if not p_tokens: continue

        for i, g in enumerate(gold_entities):
            if i in used_gold: continue
            g_tokens = set(normalize_text(g["text"]).split())

            # Jika tipe sama dan ada overlap token
            if p["type"] == g["type"] and (p_tokens & g_tokens):
                tp += 1
                used_gold.add(i)
                break

    fp = len(pred_entities) - tp
    fn = len(gold_entities) - tp
    return tp, fp, fn

def fuzzy_match(pred_entities, gold_entities, threshold=60):
    tp = 0
    used_gold = set()
    for p in pred_entities:
        for i, g in enumerate(gold_entities):
            if i in used_gold or p["type"] != g["type"]: continue

            score = fuzz.token_set_ratio(normalize_text(p["text"]), normalize_text(g["text"]))
            if score >= threshold:
                tp += 1
                used_gold.add(i)
                break

    fp = len(pred_entities) - tp
    fn = len(gold_entities) - tp
    return tp, fp, fn

def compute_prf(tp, fp, fn):
    precision = tp / (tp + fp) if tp + fp > 0 else 0
    recall = tp / (tp + fn) if tp + fn > 0 else 0
    f1 = (2 * precision * recall / (precision + recall)) if precision + recall > 0 else 0
    return precision, recall, f1

# ==========================================
# 4. PROSES EVALUASI
# ==========================================
def run_evaluation():
    # Ambil daftar unik article_id yang ada di Ground Truth
    list_article_id = df_gold['article_id'].unique()

    overall_metrics = {"exact": [0,0,0], "relaxed": [0,0,0], "fuzzy": [0,0,0]}

    print(f"Memulai evaluasi pada {len(list_article_id)} artikel...")

    for article_id in list_article_id:
        # 1. Ambil Prediksi GPT-4o untuk artikel ini
        pred_data = df_preds[df_preds["article_id"] == article_id]

        pred_entities = []
        seen_preds = set()

        for _, r in pred_data.iterrows():
            clean_text = str(r["entity"]).strip()
            clean_type = str(r["entity_type"]).strip()

            # Logika Unikalisasi (Identik dengan script BERT)
            identifier = (normalize_text(clean_text), clean_type)
            if identifier not in seen_preds and len(clean_text) > 1:
                pred_entities.append({"text": clean_text, "type": clean_type})
                seen_preds.add(identifier)

        # 2. Ambil Ground Truth untuk artikel ini
        gold_data = df_gold[df_gold["article_id"] == article_id]
        gold_entities = [{"text": r["entity"], "type": r["entity_type"]} for _, r in gold_data.iterrows()]

        # 3. Hitung TP, FP, FN per metode
        for mode, func in [("exact", exact_match), ("relaxed", relaxed_match), ("fuzzy", fuzzy_match)]:
            tp, fp, fn = func(pred_entities, gold_entities)
            overall_metrics[mode][0] += tp
            overall_metrics[mode][1] += fp
            overall_metrics[mode][2] += fn

    # 4. Rekapitulasi Hasil Akhir (Micro Average)
    final_report = []
    for mode in ["exact", "relaxed", "fuzzy"]:
        tp, fp, fn = overall_metrics[mode]
        p, r, f1 = compute_prf(tp, fp, fn)
        final_report.append({
            "Method": mode.capitalize(),
            "Precision": round(p, 4),
            "Recall": round(r, 4),
            "F1-Score": round(f1, 4),
            "TP": tp,
            "FP": fp,
            "FN": fn
        })

    df_report = pd.DataFrame(final_report)
    print("\n" + "="*50)
    print("HASIL EVALUASI GPT-4o (MICRO AVERAGE)")
    print("="*50)
    print(df_report)

if __name__ == "__main__":
    run_evaluation()

"""2-Shot Prompting"""

# ==========================================
# 2. CONFIGURATION & LOAD DATA
# ==========================================
# Ganti nama file jika berbeda
PREDICTION_FILE = "gpt5_(3)_Two-Shot.csv"
GROUND_TRUTH_FILE = "GroundTruth_2Shot.csv"

# Load Data
df_preds = pd.read_csv(PREDICTION_FILE)
df_gold = pd.read_csv(GROUND_TRUTH_FILE)

# Bersihkan spasi di nama kolom
df_preds.columns = df_preds.columns.str.strip()
df_gold.columns = df_gold.columns.str.strip()

# ==========================================
# 3. FUNGSI EVALUASI (Sesuai Logika BERT)
# ==========================================
def normalize_text(text):
    if pd.isna(text): return ""
    text = str(text).lower()
    text = text.replace("##", "") # Antisipasi sisa sub-word
    text = re.sub(r"[^\w\s]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

def exact_match(pred_entities, gold_entities):
    # Set-based evaluation
    pred_set = {(normalize_text(e["text"]), e["type"]) for e in pred_entities}
    gold_set = {(normalize_text(g["text"]), g["type"]) for g in gold_entities}

    tp = len(pred_set & gold_set)
    fp = len(pred_set - gold_set)
    fn = len(gold_set - pred_set)
    return tp, fp, fn

def relaxed_match(pred_entities, gold_entities):
    tp = 0
    used_gold = set()
    # Meniru logika iteratif dari script BERT
    for p in pred_entities:
        p_tokens = set(normalize_text(p["text"]).split())
        if not p_tokens: continue

        for i, g in enumerate(gold_entities):
            if i in used_gold: continue
            g_tokens = set(normalize_text(g["text"]).split())

            # Jika tipe sama dan ada overlap token
            if p["type"] == g["type"] and (p_tokens & g_tokens):
                tp += 1
                used_gold.add(i)
                break

    fp = len(pred_entities) - tp
    fn = len(gold_entities) - tp
    return tp, fp, fn

def fuzzy_match(pred_entities, gold_entities, threshold=60):
    tp = 0
    used_gold = set()
    for p in pred_entities:
        for i, g in enumerate(gold_entities):
            if i in used_gold or p["type"] != g["type"]: continue

            score = fuzz.token_set_ratio(normalize_text(p["text"]), normalize_text(g["text"]))
            if score >= threshold:
                tp += 1
                used_gold.add(i)
                break

    fp = len(pred_entities) - tp
    fn = len(gold_entities) - tp
    return tp, fp, fn

def compute_prf(tp, fp, fn):
    precision = tp / (tp + fp) if tp + fp > 0 else 0
    recall = tp / (tp + fn) if tp + fn > 0 else 0
    f1 = (2 * precision * recall / (precision + recall)) if precision + recall > 0 else 0
    return precision, recall, f1

# ==========================================
# 4. PROSES EVALUASI
# ==========================================
def run_evaluation():
    # Ambil daftar unik article_id yang ada di Ground Truth
    list_article_id = df_gold['article_id'].unique()

    overall_metrics = {"exact": [0,0,0], "relaxed": [0,0,0], "fuzzy": [0,0,0]}

    print(f"Memulai evaluasi pada {len(list_article_id)} artikel...")

    for article_id in list_article_id:
        # 1. Ambil Prediksi GPT-4o untuk artikel ini
        pred_data = df_preds[df_preds["article_id"] == article_id]

        pred_entities = []
        seen_preds = set()

        for _, r in pred_data.iterrows():
            clean_text = str(r["entity"]).strip()
            clean_type = str(r["entity_type"]).strip()

            # Logika Unikalisasi (Identik dengan script BERT)
            identifier = (normalize_text(clean_text), clean_type)
            if identifier not in seen_preds and len(clean_text) > 1:
                pred_entities.append({"text": clean_text, "type": clean_type})
                seen_preds.add(identifier)

        # 2. Ambil Ground Truth untuk artikel ini
        gold_data = df_gold[df_gold["article_id"] == article_id]
        gold_entities = [{"text": r["entity"], "type": r["entity_type"]} for _, r in gold_data.iterrows()]

        # 3. Hitung TP, FP, FN per metode
        for mode, func in [("exact", exact_match), ("relaxed", relaxed_match), ("fuzzy", fuzzy_match)]:
            tp, fp, fn = func(pred_entities, gold_entities)
            overall_metrics[mode][0] += tp
            overall_metrics[mode][1] += fp
            overall_metrics[mode][2] += fn

    # 4. Rekapitulasi Hasil Akhir (Micro Average)
    final_report = []
    for mode in ["exact", "relaxed", "fuzzy"]:
        tp, fp, fn = overall_metrics[mode]
        p, r, f1 = compute_prf(tp, fp, fn)
        final_report.append({
            "Method": mode.capitalize(),
            "Precision": round(p, 4),
            "Recall": round(r, 4),
            "F1-Score": round(f1, 4),
            "TP": tp,
            "FP": fp,
            "FN": fn
        })

    df_report = pd.DataFrame(final_report)
    print("\n" + "="*50)
    print("HASIL EVALUASI GPT-4o (MICRO AVERAGE)")
    print("="*50)
    print(df_report)

if __name__ == "__main__":
    run_evaluation()

"""3-Shot Prompting"""

# ==========================================
# 2. CONFIGURATION & LOAD DATA
# ==========================================
# Ganti nama file jika berbeda
PREDICTION_FILE = "gpt5_(3)_Three-Shot.csv"
GROUND_TRUTH_FILE = "GroundTruth_3Shot.csv"

# Load Data
df_preds = pd.read_csv(PREDICTION_FILE)
df_gold = pd.read_csv(GROUND_TRUTH_FILE)

# Bersihkan spasi di nama kolom
df_preds.columns = df_preds.columns.str.strip()
df_gold.columns = df_gold.columns.str.strip()

# ==========================================
# 3. FUNGSI EVALUASI (Sesuai Logika BERT)
# ==========================================
def normalize_text(text):
    if pd.isna(text): return ""
    text = str(text).lower()
    text = text.replace("##", "") # Antisipasi sisa sub-word
    text = re.sub(r"[^\w\s]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

def exact_match(pred_entities, gold_entities):
    # Set-based evaluation
    pred_set = {(normalize_text(e["text"]), e["type"]) for e in pred_entities}
    gold_set = {(normalize_text(g["text"]), g["type"]) for g in gold_entities}

    tp = len(pred_set & gold_set)
    fp = len(pred_set - gold_set)
    fn = len(gold_set - pred_set)
    return tp, fp, fn

def relaxed_match(pred_entities, gold_entities):
    tp = 0
    used_gold = set()
    # Meniru logika iteratif dari script BERT
    for p in pred_entities:
        p_tokens = set(normalize_text(p["text"]).split())
        if not p_tokens: continue

        for i, g in enumerate(gold_entities):
            if i in used_gold: continue
            g_tokens = set(normalize_text(g["text"]).split())

            # Jika tipe sama dan ada overlap token
            if p["type"] == g["type"] and (p_tokens & g_tokens):
                tp += 1
                used_gold.add(i)
                break

    fp = len(pred_entities) - tp
    fn = len(gold_entities) - tp
    return tp, fp, fn

def fuzzy_match(pred_entities, gold_entities, threshold=60):
    tp = 0
    used_gold = set()
    for p in pred_entities:
        for i, g in enumerate(gold_entities):
            if i in used_gold or p["type"] != g["type"]: continue

            score = fuzz.token_set_ratio(normalize_text(p["text"]), normalize_text(g["text"]))
            if score >= threshold:
                tp += 1
                used_gold.add(i)
                break

    fp = len(pred_entities) - tp
    fn = len(gold_entities) - tp
    return tp, fp, fn

def compute_prf(tp, fp, fn):
    precision = tp / (tp + fp) if tp + fp > 0 else 0
    recall = tp / (tp + fn) if tp + fn > 0 else 0
    f1 = (2 * precision * recall / (precision + recall)) if precision + recall > 0 else 0
    return precision, recall, f1

# ==========================================
# 4. PROSES EVALUASI
# ==========================================
def run_evaluation():
    # Ambil daftar unik article_id yang ada di Ground Truth
    list_article_id = df_gold['article_id'].unique()

    overall_metrics = {"exact": [0,0,0], "relaxed": [0,0,0], "fuzzy": [0,0,0]}

    print(f"Memulai evaluasi pada {len(list_article_id)} artikel...")

    for article_id in list_article_id:
        # 1. Ambil Prediksi GPT-4o untuk artikel ini
        pred_data = df_preds[df_preds["article_id"] == article_id]

        pred_entities = []
        seen_preds = set()

        for _, r in pred_data.iterrows():
            clean_text = str(r["entity"]).strip()
            clean_type = str(r["entity_type"]).strip()

            # Logika Unikalisasi (Identik dengan script BERT)
            identifier = (normalize_text(clean_text), clean_type)
            if identifier not in seen_preds and len(clean_text) > 1:
                pred_entities.append({"text": clean_text, "type": clean_type})
                seen_preds.add(identifier)

        # 2. Ambil Ground Truth untuk artikel ini
        gold_data = df_gold[df_gold["article_id"] == article_id]
        gold_entities = [{"text": r["entity"], "type": r["entity_type"]} for _, r in gold_data.iterrows()]

        # 3. Hitung TP, FP, FN per metode
        for mode, func in [("exact", exact_match), ("relaxed", relaxed_match), ("fuzzy", fuzzy_match)]:
            tp, fp, fn = func(pred_entities, gold_entities)
            overall_metrics[mode][0] += tp
            overall_metrics[mode][1] += fp
            overall_metrics[mode][2] += fn

    # 4. Rekapitulasi Hasil Akhir (Micro Average)
    final_report = []
    for mode in ["exact", "relaxed", "fuzzy"]:
        tp, fp, fn = overall_metrics[mode]
        p, r, f1 = compute_prf(tp, fp, fn)
        final_report.append({
            "Method": mode.capitalize(),
            "Precision": round(p, 4),
            "Recall": round(r, 4),
            "F1-Score": round(f1, 4),
            "TP": tp,
            "FP": fp,
            "FN": fn
        })

    df_report = pd.DataFrame(final_report)
    print("\n" + "="*50)
    print("HASIL EVALUASI GPT-4o (MICRO AVERAGE)")
    print("="*50)
    print(df_report)

if __name__ == "__main__":
    run_evaluation()