# -*- coding: utf-8 -*-
"""Skripsi-GPT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ATtLaVJJs_ivH9X7eObivMrRWRdflQOY

# Ekstraksi Infromasi Pengobatan Alternatif Untuk Kanker Dari Artikel Ilmiah Dengan *Named Entiry Recognition* Berbasis GPT

---

* Menggunakan GPT API dengan pendekatan Named Entity Recognition (NER)
* Input: Satu file .txt berisi banyak artikel (dipisah dengan '---')
* Output: CSV berisi hasil ekstraksi entitas (1 baris = 1 entitas)

---
Tipe Prompt:
1. Baseline Prompt with Role-play and Format Specification
2. Annotation Guideline-based Prompt
3. Few shot-prompting (sampai 3 shots)

---
"""

#Import lib dan API Keys
from openai import OpenAI
import pandas as pd
import time
import os
from io import StringIO
import re

KEYS = "---"

# Cek Ketersediaan Model GPT di API
from openai import OpenAI

client = OpenAI(api_key=KEYS)

models = client.models.list()
for m in models.data:
    print(m.id)

"""

---

# (1)"""

# 1. Setup API Key
client = OpenAI(api_key=KEYS)

# 2. Template Prompt untuk GPT-4o
prompt_template = """
You are a highly accurate Named Entity Recognition (NER) system specialized in identifying entities related to alternative medicine for cancer based on herbal plants.

Your task:
- Extract the following entity types: Herbs Scientific Name (HSN), Local Name (LN), Part of Herb (PH), Ingredient (IG), Disease (DS), Cell Line (CL), and Target (TG).
- Extract entities only from the title and abstract of the provided text.
- For each extracted entity, output one row in **TSV (Tab-Separated Values)** format with the columns:
  entity_ID\tentity\tentity_type\tsentence

Format Specification:
- The "entity_ID" column should contain a unique integer starting from 1 for each entity in each article.
- The "entity_type" column must be one of: Herbs Scientific Name (HSN), Local Name (LN), Part of Herb (PH), Ingredient (IG), Disease (DS), Cell Line (CL), and Target (TG). (Just use the abbreviation)
- The "sentence" column must contain the exact sentence where the entity appears.
- **IMPORTANT: Any field (especially 'entity' and 'sentence') that contains a comma (,) MUST be enclosed in double quotes (").**
- Do not infer or add entities that do not explicitly appear in the text.
- A sentence may be repeated across multiple rows as needed if it contains more than one entity.
- If an entity has already been annotated and it appears again later in the text, annotate it only once.
- Output MUST be a valid **TSV snippet** with header:
  entity_ID\tentity\tentity_type\tsentence
- Do NOT include any explanation, comments, or surrounding text.
- Do NOT wrap the TSV in markdown code fences.

Text:
{article_text}
"""

# 3. Fungsi ekstraksi entitas (per artikel)
def extract_entities(article_text: str) -> str | None:
    try:
        response = client.chat.completions.create(
            model="gpt-4o",
            temperature=0,
            messages=[
                {"role": "system", "content": "You are a biomedical NER extractor."},
                {"role": "user", "content": prompt_template.format(article_text=article_text)}
            ]
        )
        content = response.choices[0].message.content.strip()

        # Antisipasi kalau model ngeyel dan ngasih ```csv ... ``` (kita bersihin)
        if content.startswith("```"):
            # buang ```...``` di awal/akhir
            content = re.sub(r"^```[a-zA-Z]*\n?", "", content)
            content = re.sub(r"\n?```$", "", content).strip()

        return content
    except Exception as e:
        print("❌ Error:", e)
        return None

# 4. Baca file teks
input_file = "Data Abstrak Paper.txt"
output_file = "gpt4o_(1).csv"

with open(input_file, "r", encoding="utf-8") as f:
    content = f.read()

# 5. Pisahkan artikel berdasarkan pemisah '---'
articles = [a.strip() for a in content.split("---") if a.strip()]
print(f"📄 Ditemukan {len(articles)} artikel untuk diproses.\n")

# 6. Loop ekstraksi untuk tiap artikel
all_dfs = []

for i, article_text in enumerate(articles, start=1):
    print(f"🔍 Memproses artikel {i}/{len(articles)}...")
    csv_snippet = extract_entities(article_text)

    if not csv_snippet:
        print(f"⚠️ Tidak ada output untuk artikel {i}, dilewati.")
        continue

    try:
        # Parse output TSV dari GPT jadi DataFrame, menggunakan '\t' sebagai pemisah
        df_article = pd.read_csv(StringIO(csv_snippet), sep='\t')

        # Tambahkan kolom article_id agar bisa dilacak ke artikel asal
        df_article.insert(0, "article_id", "A" + str(i))

        all_dfs.append(df_article)
    except Exception as e:
        print(f"⚠️ Gagal parse CSV untuk artikel {i}: **{e}**")
        print("Output mentah GPT:")
        print(csv_snippet)
        continue

    time.sleep(2) # jeda antar request untuk jaga-jaga rate limit

# 7. Gabungkan semua hasil dan simpan ke CSV
if all_dfs:
    df = pd.concat(all_dfs, ignore_index=True)
    df.to_csv(output_file, index=False, encoding="utf-8")
    print(f"\n✅ Ekstraksi selesai! Hasil disimpan di: **{output_file}**")
else:
    print("\n⚠️ Tidak ada data yang berhasil diekstraksi.")

"""
---

# (2)

"""

# 1. Setup API Key
client = OpenAI(api_key=KEYS)

# 2. Template Prompt untuk GPT-4o
prompt_template = """
You are a highly accurate Named Entity Recognition (NER) system specialized in identifying entities related to alternative medicine for cancer based on herbal plants.

Your task:
- Extract the following entity types: Herbs Scientific Name (HSN), Local Name (LN), Part of Herb (PH), Ingredient (IG), Disease (DS), Cell Line (CL), and Target (TG).
- Extract entities only from the title and abstract of the provided text.
- For each extracted entity, output one row in **TSV (Tab-Separated Values)** format with the columns:
  entity_ID\tentity\tentity_type\tsentence

Format Specification:
- The "entity_ID" column should contain a unique integer starting from 1 for each entity in each article.
- The "entity_type" column must be one of: Herbs Scientific Name (HSN), Local Name (LN), Part of Herb (PH), Ingredient (IG), Disease (DS), Cell Line (CL), and Target (TG). (Just use the abbreviation)
- The "sentence" column must contain the exact sentence where the entity appears.
- **IMPORTANT: Any field (especially 'entity' and 'sentence') that contains a comma (,) MUST be enclosed in double quotes (").**
- Do not infer or add entities that do not explicitly appear in the text.
- A sentence may be repeated across multiple rows as needed if it contains more than one entity.
- If an entity has already been annotated and it appears again later in the text, annotate it only once.
- Output MUST be a valid **TSV snippet** with header:
  entity_ID\tentity\tentity_type\tsentence
- Do NOT include any explanation, comments, or surrounding text.
- Do NOT wrap the TSV in markdown code fences.

(a) Entity Definitions
  (i) Herb Scientific Name: The scientific name of the plant or plant part used for cancer treatment.
  (ii) Local Name: The local or regional name of the medicinal plant, including common names used in Indonesian or local dialects.
  (iii) Part of the Herb: The specific part of the plant used in the study or extraction process.
  (iv) Ingredient: A chemical substance or compound contained in the plant that has a biological role in combating cancer.
  (v) Disease Name: The type of cancer mentioned in the context of the plant’s or active ingredient’s biological effects.
  (vi) Cell Line: The name of the cancer cell line used in biological or in-vitro experiments.
  (vii) Target: A biological molecule or pathway involved in cancer and targeted by the plant’s active compounds during treatment.

(b) Scope
  (i) Only annotate the title and abstract.
  (ii) Plural nouns must be annotated in singular form. Example: “cervical cancers” → “cervical cancer”
  (iii) Only annotate explicitly mentioned entity phrases. Do not guess, infer, or add interpretations.


(c) Annotation Guidelines
  (i) Use entities in their simplest base form. Do not include unnecessary modifiers.
    - Incorrect: “severe lung cancer”
    - Correct: “lung cancer”
  (ii) Do not annotate partial segments of an entity.
    - Incorrect: Annotating “lung” from “lung cancer”
  (iii) Terms that function only as modifiers within a noun phrase should not be annotated separately.
    Example: In “cancer treatment”, the word “cancer” is not annotated separately if the entity of interest is “cancer treatment”.
  (iv) Articles (a, an, the) and possessive forms (his, her, patient’s, etc.) are not annotated.
    Example sentence: “a rhizome of kunyit is recorded to have an effect on breast cancer”
    - Incorrect: “a rhizome”
    - Correct: “rhizome”, “kunyit”, “breast cancer”
  (v) Conjunctions such as “and”, “or”, and list structures are not annotated.
    - Incorrect: “HeLa, A549, and B16 cell” as one span
    - Correct: Annotate individually: “HeLa”, “A549”, “B16”
  (vi) When a concept is expressed in two forms (e.g., acronym and full form), annotate them as one entity.
    Example: “HeLa (Human cervical carcinoma cell line)” → treated as a single entity span.
  (vii) Do not annotate:
    a. Pronouns or references such as “this plant”, “its benefit”
    b. Negative claims such as “does not reduce cancer risk”
    c. Generic non-specific terms such as “medicine”, “research” without domain relevance

Text:
{article_text}
"""

# 3. Fungsi ekstraksi entitas (per artikel)
def extract_entities(article_text: str) -> str | None:
    try:
        response = client.chat.completions.create(
            model="gpt-4o", #coba versi gpt-4 Turbo, gpt-5
            temperature=0,
            messages=[
                {"role": "system", "content": "You are a biomedical NER extractor."},
                {"role": "user", "content": prompt_template.format(article_text=article_text)}
            ]
        )
        content = response.choices[0].message.content.strip()

        # Antisipasi kalau model ngeyel dan ngasih ```csv ... ``` (kita bersihin)
        if content.startswith("```"):
            # buang ```...``` di awal/akhir
            content = re.sub(r"^```[a-zA-Z]*\n?", "", content)
            content = re.sub(r"\n?```$", "", content).strip()

        return content
    except Exception as e:
        print("❌ Error:", e)
        return None

# 4. Baca file teks
input_file = "Data Abstrak Paper.txt"
output_file = "gpt4o_(2).csv"

with open(input_file, "r", encoding="utf-8") as f:
    content = f.read()

# 5. Pisahkan artikel berdasarkan pemisah '---'
articles = [a.strip() for a in content.split("---") if a.strip()]
print(f"📄 Ditemukan {len(articles)} artikel untuk diproses.\n")

# 6. Loop ekstraksi untuk tiap artikel
all_dfs = []

for i, article_text in enumerate(articles, start=1):
    print(f"🔍 Memproses artikel {i}/{len(articles)}...")
    csv_snippet = extract_entities(article_text)

    if not csv_snippet:
        print(f"⚠️ Tidak ada output untuk artikel {i}, dilewati.")
        continue

    try:
        # Parse output TSV dari GPT jadi DataFrame, menggunakan '\t' sebagai pemisah
        df_article = pd.read_csv(StringIO(csv_snippet), sep='\t')

        # Tambahkan kolom article_id agar bisa dilacak ke artikel asal
        df_article.insert(0, "article_id", "A" + str(i))

        all_dfs.append(df_article)
    except Exception as e:
        print(f"⚠️ Gagal parse CSV untuk artikel {i}: **{e}**")
        print("Output mentah GPT:")
        print(csv_snippet)
        continue

    time.sleep(2) # jeda antar request untuk jaga-jaga rate limit

# 7. Gabungkan semua hasil dan simpan ke CSV
if all_dfs:
    df = pd.concat(all_dfs, ignore_index=True)
    df.to_csv(output_file, index=False, encoding="utf-8")
    print(f"\n✅ Ekstraksi selesai! Hasil disimpan di: **{output_file}**")
else:
    print("\n⚠️ Tidak ada data yang berhasil diekstraksi.")

"""---

# (3)

1-Shot Prompting
"""

# 1. Setup API Key
client = OpenAI(api_key=KEYS)

# 2. Template Prompt untuk GPT-4o
prompt_template = """
You are a highly accurate Named Entity Recognition (NER) system specialized in identifying entities related to alternative medicine for cancer based on herbal plants.

Your task:
- Extract the following entity types: Herbs Scientific Name (HSN), Local Name (LN), Part of Herb (PH), Ingredient (IG), Disease (DS), Cell Line (CL), and Target (TG).
- Extract entities only from the title and abstract of the provided text.
- For each extracted entity, output one row in **TSV (Tab-Separated Values)** format with the columns:
  entity_ID\tentity\tentity_type\tsentence

Format Specification:
- The "entity_ID" column should contain a unique integer starting from 1 for each entity in each article.
- The "entity_type" column must be one of: Herbs Scientific Name (HSN), Local Name (LN), Part of Herb (PH), Ingredient (IG), Disease (DS), Cell Line (CL), and Target (TG). (Just use the abbreviation)
- The "sentence" column must contain the exact sentence where the entity appears.
- **IMPORTANT: Any field (especially 'entity' and 'sentence') that contains a comma (,) MUST be enclosed in double quotes (").**
- Do not infer or add entities that do not explicitly appear in the text.
- A sentence may be repeated across multiple rows as needed if it contains more than one entity.
- If an entity has already been annotated and it appears again later in the text, annotate it only once.
- Output MUST be a valid **TSV snippet** with header:
  entity_ID\tentity\tentity_type\tsentence
- Do NOT include any explanation, comments, or surrounding text.
- Do NOT wrap the TSV in markdown code fences.

(a) Entity Definitions
  (i) Herb Scientific Name: The scientific name of the plant or plant part used for cancer treatment.
  (ii) Local Name: The local or regional name of the medicinal plant, including common names used in Indonesian or local dialects.
  (iii) Part of the Herb: The specific part of the plant used in the study or extraction process.
  (iv) Ingredient: A chemical substance or compound contained in the plant that has a biological role in combating cancer.
  (v) Disease Name: The type of cancer mentioned in the context of the plant’s or active ingredient’s biological effects.
  (vi) Cell Line: The name of the cancer cell line used in biological or in-vitro experiments.
  (vii) Target: A biological molecule or pathway involved in cancer and targeted by the plant’s active compounds during treatment.

(b) Scope
  (i) Only annotate the title and abstract.
  (ii) Plural nouns must be annotated in singular form. Example: “cervical cancers” → “cervical cancer”
  (iii) Only annotate explicitly mentioned entity phrases. Do not guess, infer, or add interpretations.

(c) Annotation Guidelines
  (i) Use entities in their simplest base form. Do not include unnecessary modifiers.
    - Incorrect: “severe lung cancer”
    - Correct: “lung cancer”
  (ii) Do not annotate partial segments of an entity.
    - Incorrect: Annotating “lung” from “lung cancer”
  (iii) Terms that function only as modifiers within a noun phrase should not be annotated separately.
    Example: In “cancer treatment”, the word “cancer” is not annotated separately if the entity of interest is “cancer treatment”.
  (iv) Articles (a, an, the) and possessive forms (his, her, patient’s, etc.) are not annotated.
    Example sentence: “a rhizome of kunyit is recorded to have an effect on breast cancer”
    - Incorrect: “a rhizome”
    - Correct: “rhizome”, “kunyit”, “breast cancer”
  (v) Conjunctions such as “and”, “or”, and list structures are not annotated.
    - Incorrect: “HeLa, A549, and B16 cell” as one span
    - Correct: Annotate individually: “HeLa”, “A549”, “B16”
  (vi) When a concept is expressed in two forms (e.g., acronym and full form), annotate them as one entity.
    Example: “HeLa (Human cervical carcinoma cell line)” → treated as a single entity span.
  (vii) Do not annotate:
    a. Pronouns or references such as “this plant”, “its benefit”
    b. Negative claims such as “does not reduce cancer risk”
    c. Generic non-specific terms such as “medicine”, “research” without domain relevance

(d) Examples
Example Input1:
  Antidiabetic, cytotoxic and antioxidant activities of Rhodomyrtus tomentosa leaf extracts.
  Idris M(1)(2), Sukandar ER(1), Purnomo AS(1), Martak F(1), Fatmawati S(1)(3).
  As part of our project on exploring Indonesian medicinal plants for antidiabetic and anticancer agents, this study was conducted to investigate the total phenolic and flavonoid contents, and antioxidant, cytotoxic and antidiabetic properties of R. tomentosa leaf extracts. The antioxidant activity was tested using DPPH, ABTS, and FRAP methods. In vitro cytotoxic assay was performed against MCF-7, HeLa, A549, and B16 cancer cell lines. The in vitro antidiabetic testing was determined using α-glucosidase and α-amylase inhibitory evaluation, while STZ-induced diabetic rats were used for in vivo study. The highest values of total phenolic (191.97 ± 0.19 mg GAE g-1) and flavonoid (29.11 ± 0.05 mg QE g-1) contents were recorded in methanolic extract. This extract also showed the highest DPPH and ABTS activities with IC50 values of 7.79 ± 0.03 and 4.03 ± 0.02 μg mL-1, respectively, as well as the highest FRAP activity with a value of 64.05 ± 0.54 μM Fe2+ g-1. The methanol extract had cytotoxicity against MCF-7, HeLa, A549, and B16 cancer cell lines with IC50 values of 123.49 ± 0.79, 28.28 ± 0.17, 168.88 ± 1.14, and 42.44 ± 0.18 μg mL-1, respectively. In vitro antidiabetic evaluation indicated that the MeOH extract inhibited α-glucosidase and α-amylase with IC50 values of 45.73 ± 1.06 and 41.31 ± 1.12 μg mL-1, respectively. A dose of 400 mg kg-1 body weight of the MeOH extract reduced rats' blood glucose rate and serum blood glucose by 48.51% and 17.73%, respectively after 15 days of treatment. Taken together, these findings suggested that the methanolic extract of R. tomentosa leaves can be used as a potential source of antioxidant, cytotoxic, and antidiabetic agents.

Example Output1:
  a. Rhodomyrtus tomentosa = HSN
  b. Leaf = PH
  c. MCF-7 = CL
  d. HeLa = CL
  e. A549 = CL
  f. B16 = CL
  g. Phenolic = IG
  h. Flavonoid = IG
  i. Sesterpenoid = IG

Text:
{article_text}
"""

# 3. Fungsi ekstraksi entitas (per artikel)
def extract_entities(article_text: str) -> str | None:
    try:
        response = client.chat.completions.create(
            model="gpt-4o", #coba versi gpt-4 Turbo, gpt-5
            temperature=0,
            messages=[
                {"role": "system", "content": "You are a biomedical NER extractor."},
                {"role": "user", "content": prompt_template.format(article_text=article_text)}
            ]
        )
        content = response.choices[0].message.content.strip()

        # Antisipasi kalau model ngeyel dan ngasih ```csv ... ``` (kita bersihin)
        if content.startswith("```"):
            # buang ```...``` di awal/akhir
            content = re.sub(r"^```[a-zA-Z]*\n?", "", content)
            content = re.sub(r"\n?```$", "", content).strip()

        return content
    except Exception as e:
        print("❌ Error:", e)
        return None

# 4. Baca file teks
input_file = "Data Abstrak Paper.txt"
output_file = "gpt4o_(3)_One-Shot.csv"

with open(input_file, "r", encoding="utf-8") as f:
    content = f.read()

# 5. Pisahkan artikel berdasarkan pemisah '---'
articles = [a.strip() for a in content.split("---") if a.strip()]
print(f"📄 Ditemukan {len(articles)} artikel untuk diproses.\n")

# 6. Loop ekstraksi untuk tiap artikel
all_dfs = []

for i, article_text in enumerate(articles, start=1):
    print(f"🔍 Memproses artikel {i}/{len(articles)}...")
    csv_snippet = extract_entities(article_text)

    if not csv_snippet:
        print(f"⚠️ Tidak ada output untuk artikel {i}, dilewati.")
        continue

    try:
        # Parse output TSV dari GPT jadi DataFrame, menggunakan '\t' sebagai pemisah
        df_article = pd.read_csv(StringIO(csv_snippet), sep='\t')

        # Tambahkan kolom article_id agar bisa dilacak ke artikel asal
        df_article.insert(0, "article_id", "A" + str(i))

        all_dfs.append(df_article)
    except Exception as e:
        print(f"⚠️ Gagal parse CSV untuk artikel {i}: **{e}**")
        print("Output mentah GPT:")
        print(csv_snippet)
        continue

    time.sleep(2) # jeda antar request untuk jaga-jaga rate limit

# 7. Gabungkan semua hasil dan simpan ke CSV
if all_dfs:
    df = pd.concat(all_dfs, ignore_index=True)
    df.to_csv(output_file, index=False, encoding="utf-8")
    print(f"\n✅ Ekstraksi selesai! Hasil disimpan di: **{output_file}**")
else:
    print("\n⚠️ Tidak ada data yang berhasil diekstraksi.")

"""2-Shot Prompting"""

# 1. Setup API Key
client = OpenAI(api_key=KEYS)

# 2. Template Prompt untuk GPT-4o
prompt_template = """
You are a highly accurate Named Entity Recognition (NER) system specialized in identifying entities related to alternative medicine for cancer based on herbal plants.

Your task:
- Extract the following entity types: Herbs Scientific Name (HSN), Local Name (LN), Part of Herb (PH), Ingredient (IG), Disease (DS), Cell Line (CL), and Target (TG).
- Extract entities only from the title and abstract of the provided text.
- For each extracted entity, output one row in **TSV (Tab-Separated Values)** format with the columns:
  entity_ID\tentity\tentity_type\tsentence

Format Specification:
- The "entity_ID" column should contain a unique integer starting from 1 for each entity in each article.
- The "entity_type" column must be one of: Herbs Scientific Name (HSN), Local Name (LN), Part of Herb (PH), Ingredient (IG), Disease (DS), Cell Line (CL), and Target (TG). (Just use the abbreviation)
- The "sentence" column must contain the exact sentence where the entity appears.
- **IMPORTANT: Any field (especially 'entity' and 'sentence') that contains a comma (,) MUST be enclosed in double quotes (").**
- Do not infer or add entities that do not explicitly appear in the text.
- A sentence may be repeated across multiple rows as needed if it contains more than one entity.
- If an entity has already been annotated and it appears again later in the text, annotate it only once.
- Output MUST be a valid **TSV snippet** with header:
  entity_ID\tentity\tentity_type\tsentence
- Do NOT include any explanation, comments, or surrounding text.
- Do NOT wrap the TSV in markdown code fences.

(a) Entity Definitions
  (i) Herb Scientific Name: The scientific name of the plant or plant part used for cancer treatment.
  (ii) Local Name: The local or regional name of the medicinal plant, including common names used in Indonesian or local dialects.
  (iii) Part of the Herb: The specific part of the plant used in the study or extraction process.
  (iv) Ingredient: A chemical substance or compound contained in the plant that has a biological role in combating cancer.
  (v) Disease Name: The type of cancer mentioned in the context of the plant’s or active ingredient’s biological effects.
  (vi) Cell Line: The name of the cancer cell line used in biological or in-vitro experiments.
  (vii) Target: A biological molecule or pathway involved in cancer and targeted by the plant’s active compounds during treatment.

(b) Scope
  (i) Only annotate the title and abstract.
  (ii) Plural nouns must be annotated in singular form. Example: “cervical cancers” → “cervical cancer”
  (iii) Only annotate explicitly mentioned entity phrases. Do not guess, infer, or add interpretations.

(c) Annotation Guidelines
  (i) Use entities in their simplest base form. Do not include unnecessary modifiers.
    - Incorrect: “severe lung cancer”
    - Correct: “lung cancer”
  (ii) Do not annotate partial segments of an entity.
    - Incorrect: Annotating “lung” from “lung cancer”
  (iii) Terms that function only as modifiers within a noun phrase should not be annotated separately.
    Example: In “cancer treatment”, the word “cancer” is not annotated separately if the entity of interest is “cancer treatment”.
  (iv) Articles (a, an, the) and possessive forms (his, her, patient’s, etc.) are not annotated.
    Example sentence: “a rhizome of kunyit is recorded to have an effect on breast cancer”
    - Incorrect: “a rhizome”
    - Correct: “rhizome”, “kunyit”, “breast cancer”
  (v) Conjunctions such as “and”, “or”, and list structures are not annotated.
    - Incorrect: “HeLa, A549, and B16 cell” as one span
    - Correct: Annotate individually: “HeLa”, “A549”, “B16”
  (vi) When a concept is expressed in two forms (e.g., acronym and full form), annotate them as one entity.
    Example: “HeLa (Human cervical carcinoma cell line)” → treated as a single entity span.
  (vii) Do not annotate:
    a. Pronouns or references such as “this plant”, “its benefit”
    b. Negative claims such as “does not reduce cancer risk”
    c. Generic non-specific terms such as “medicine”, “research” without domain relevance

(d) Examples
Example Input1:
  Antidiabetic, cytotoxic and antioxidant activities of Rhodomyrtus tomentosa leaf extracts.
  Idris M(1)(2), Sukandar ER(1), Purnomo AS(1), Martak F(1), Fatmawati S(1)(3).
  As part of our project on exploring Indonesian medicinal plants for antidiabetic and anticancer agents, this study was conducted to investigate the total phenolic and flavonoid contents, and antioxidant, cytotoxic and antidiabetic properties of R. tomentosa leaf extracts. The antioxidant activity was tested using DPPH, ABTS, and FRAP methods. In vitro cytotoxic assay was performed against MCF-7, HeLa, A549, and B16 cancer cell lines. The in vitro antidiabetic testing was determined using α-glucosidase and α-amylase inhibitory evaluation, while STZ-induced diabetic rats were used for in vivo study. The highest values of total phenolic (191.97 ± 0.19 mg GAE g-1) and flavonoid (29.11 ± 0.05 mg QE g-1) contents were recorded in methanolic extract. This extract also showed the highest DPPH and ABTS activities with IC50 values of 7.79 ± 0.03 and 4.03 ± 0.02 μg mL-1, respectively, as well as the highest FRAP activity with a value of 64.05 ± 0.54 μM Fe2+ g-1. The methanol extract had cytotoxicity against MCF-7, HeLa, A549, and B16 cancer cell lines with IC50 values of 123.49 ± 0.79, 28.28 ± 0.17, 168.88 ± 1.14, and 42.44 ± 0.18 μg mL-1, respectively. In vitro antidiabetic evaluation indicated that the MeOH extract inhibited α-glucosidase and α-amylase with IC50 values of 45.73 ± 1.06 and 41.31 ± 1.12 μg mL-1, respectively. A dose of 400 mg kg-1 body weight of the MeOH extract reduced rats' blood glucose rate and serum blood glucose by 48.51% and 17.73%, respectively after 15 days of treatment. Taken together, these findings suggested that the methanolic extract of R. tomentosa leaves can be used as a potential source of antioxidant, cytotoxic, and antidiabetic agents.

Example Output1:
  a. Rhodomyrtus tomentosa = HSN
  b. Leaf = PH
  c. MCF-7 = CL
  d. HeLa = CL
  e. A549 = CL
  f. B16 = CL
  g. Phenolic = IG
  h. Flavonoid = IG
  i. Sesterpenoid = IG

- - -

Example Input2:
  Nano Uncaria gambir as Chemopreventive Agent Against Breast Cancer.
  Wardana AP(1), Aminah NS(1)(2), Kristanti AN(1)(2), Fahmi MZ(1), Zahrah HI(3), Widiyastuti W(4), Ajiz HA(4), Zubaidah U(5), Wiratama PA(6), Takaya Y(7).
  BACKGROUND: Breast cancer is one of the main causes of death in women. Uncaria gambir is an Indonesian herbal plant that can be used as an anti-cancer. However, herbal medicines have low bioavailability, which affects their bioactivity. Nanoencapsulation can increase bioavailability and stability of bioactive compounds in herbal medicines.
  PURPOSE: This recent finding tried to unravel anti-cancer and chemopreventive of U. gambir nano-encapsulated by Na-alginate.
  STUDY DESIGN: U. gambir bioactive compounds were isolated and characterized using UV-Vis spectrometer, FTIR, NMR and HR-MS. U. gambir extract was nanoencapsulated using Na-alginate. Anti-cancer effect was assessed by MTT assay towards T47D cell. Meanwhile, a chemopreventive analysis was carried out in breast cancer mice-induced benzo[α]pyrene. The healthy mice were divided into 8 groups comprising control and treatment.
  RESULTS: Elucidation of U. gambir ethyl acetate extract confirmed high catechin content, 89.34% (w/w). Successful nanoencapsulation of U. gambir (G-NPs) was indicated. The particle size of G-NPs was 78.40 ± 12.25 nm. Loading efficiency (LE) and loading amount (LA) of G-NPs were 97.56 ± 0.04% and 32.52 ± 0.01%, respectively. G-NPs had an EC50 value of 10.39 ± 3.50 µg/mL, which was more toxic than the EC50 value of extract towards the T47D cell line. Administration of 200 mg/kg BW G-NPs to mice induced by benzo[α]pyrene exhibited SOD and GSH levels of 13.69 ng/mL and 455.6 ng/mL. In addition, the lowest TNF-α level was 27.96 ng/mL. A dose of 100 mg/kg BW G-NPs could best increase CAT levels by 7.18 ng/mL. There was no damage or histological abnormalities found in histological analysis of the breast tissue in the group given 200 mg/kg BW G-NPs.

Example Output2:
  a. Breast cancer = DS
  b. Uncaria gambir = HSN
  c. T47D = CL
  d. Catechin = IG


Text:
{article_text}
"""

# 3. Fungsi ekstraksi entitas (per artikel)
def extract_entities(article_text: str) -> str | None:
    try:
        response = client.chat.completions.create(
            model="gpt-4o", #coba versi gpt-4 Turbo, gpt-5
            temperature=0,
            messages=[
                {"role": "system", "content": "You are a biomedical NER extractor."},
                {"role": "user", "content": prompt_template.format(article_text=article_text)}
            ]
        )
        content = response.choices[0].message.content.strip()

        # Antisipasi kalau model ngeyel dan ngasih ```csv ... ``` (kita bersihin)
        if content.startswith("```"):
            # buang ```...``` di awal/akhir
            content = re.sub(r"^```[a-zA-Z]*\n?", "", content)
            content = re.sub(r"\n?```$", "", content).strip()

        return content
    except Exception as e:
        print("❌ Error:", e)
        return None

# 4. Baca file teks
input_file = "Data Abstrak Paper.txt"
output_file = "gpt4o_(3)_Two-Shot.csv"

with open(input_file, "r", encoding="utf-8") as f:
    content = f.read()

# 5. Pisahkan artikel berdasarkan pemisah '---'
articles = [a.strip() for a in content.split("---") if a.strip()]
print(f"📄 Ditemukan {len(articles)} artikel untuk diproses.\n")

# 6. Loop ekstraksi untuk tiap artikel
all_dfs = []

for i, article_text in enumerate(articles, start=1):
    print(f"🔍 Memproses artikel {i}/{len(articles)}...")
    csv_snippet = extract_entities(article_text)

    if not csv_snippet:
        print(f"⚠️ Tidak ada output untuk artikel {i}, dilewati.")
        continue

    try:
        # Parse output TSV dari GPT jadi DataFrame, menggunakan '\t' sebagai pemisah
        df_article = pd.read_csv(StringIO(csv_snippet), sep='\t')

        # Tambahkan kolom article_id agar bisa dilacak ke artikel asal
        df_article.insert(0, "article_id", "A" + str(i))

        all_dfs.append(df_article)
    except Exception as e:
        print(f"⚠️ Gagal parse CSV untuk artikel {i}: **{e}**")
        print("Output mentah GPT:")
        print(csv_snippet)
        continue

    time.sleep(2) # jeda antar request untuk jaga-jaga rate limit

# 7. Gabungkan semua hasil dan simpan ke CSV
if all_dfs:
    df = pd.concat(all_dfs, ignore_index=True)
    df.to_csv(output_file, index=False, encoding="utf-8")
    print(f"\n✅ Ekstraksi selesai! Hasil disimpan di: **{output_file}**")
else:
    print("\n⚠️ Tidak ada data yang berhasil diekstraksi.")

"""3-Shot Prompting"""

# 1. Setup API Key
client = OpenAI(api_key=KEYS)

# 2. Template Prompt untuk GPT-4o
prompt_template = """
You are a highly accurate Named Entity Recognition (NER) system specialized in identifying entities related to alternative medicine for cancer based on herbal plants.

Your task:
- Extract the following entity types: Herbs Scientific Name (HSN), Local Name (LN), Part of Herb (PH), Ingredient (IG), Disease (DS), Cell Line (CL), and Target (TG).
- Extract entities only from the title and abstract of the provided text.
- For each extracted entity, output one row in **TSV (Tab-Separated Values)** format with the columns:
  entity_ID\tentity\tentity_type\tsentence

Format Specification:
- The "entity_ID" column should contain a unique integer starting from 1 for each entity in each article.
- The "entity_type" column must be one of: Herbs Scientific Name (HSN), Local Name (LN), Part of Herb (PH), Ingredient (IG), Disease (DS), Cell Line (CL), and Target (TG). (Just use the abbreviation)
- The "sentence" column must contain the exact sentence where the entity appears.
- **IMPORTANT: Any field (especially 'entity' and 'sentence') that contains a comma (,) MUST be enclosed in double quotes (").**
- Do not infer or add entities that do not explicitly appear in the text.
- A sentence may be repeated across multiple rows as needed if it contains more than one entity.
- If an entity has already been annotated and it appears again later in the text, annotate it only once.
- Output MUST be a valid **TSV snippet** with header:
  entity_ID\tentity\tentity_type\tsentence
- Do NOT include any explanation, comments, or surrounding text.
- Do NOT wrap the TSV in markdown code fences.

(a) Entity Definitions
  (i) Herb Scientific Name: The scientific name of the plant or plant part used for cancer treatment.
  (ii) Local Name: The local or regional name of the medicinal plant, including common names used in Indonesian or local dialects.
  (iii) Part of the Herb: The specific part of the plant used in the study or extraction process.
  (iv) Ingredient: A chemical substance or compound contained in the plant that has a biological role in combating cancer.
  (v) Disease Name: The type of cancer mentioned in the context of the plant’s or active ingredient’s biological effects.
  (vi) Cell Line: The name of the cancer cell line used in biological or in-vitro experiments.
  (vii) Target: A biological molecule or pathway involved in cancer and targeted by the plant’s active compounds during treatment.

(b) Scope
  (i) Only annotate the title and abstract.
  (ii) Plural nouns must be annotated in singular form. Example: “cervical cancers” → “cervical cancer”
  (iii) Only annotate explicitly mentioned entity phrases. Do not guess, infer, or add interpretations.

(c) Annotation Guidelines
  (i) Use entities in their simplest base form. Do not include unnecessary modifiers.
    - Incorrect: “severe lung cancer”
    - Correct: “lung cancer”
  (ii) Do not annotate partial segments of an entity.
    - Incorrect: Annotating “lung” from “lung cancer”
  (iii) Terms that function only as modifiers within a noun phrase should not be annotated separately.
    Example: In “cancer treatment”, the word “cancer” is not annotated separately if the entity of interest is “cancer treatment”.
  (iv) Articles (a, an, the) and possessive forms (his, her, patient’s, etc.) are not annotated.
    Example sentence: “a rhizome of kunyit is recorded to have an effect on breast cancer”
    - Incorrect: “a rhizome”
    - Correct: “rhizome”, “kunyit”, “breast cancer”
  (v) Conjunctions such as “and”, “or”, and list structures are not annotated.
    - Incorrect: “HeLa, A549, and B16 cell” as one span
    - Correct: Annotate individually: “HeLa”, “A549”, “B16”
  (vi) When a concept is expressed in two forms (e.g., acronym and full form), annotate them as one entity.
    Example: “HeLa (Human cervical carcinoma cell line)” → treated as a single entity span.
  (vii) Do not annotate:
    a. Pronouns or references such as “this plant”, “its benefit”
    b. Negative claims such as “does not reduce cancer risk”
    c. Generic non-specific terms such as “medicine”, “research” without domain relevance

(d) Examples
Example Input1:
  Antidiabetic, cytotoxic and antioxidant activities of Rhodomyrtus tomentosa leaf extracts.
  Idris M(1)(2), Sukandar ER(1), Purnomo AS(1), Martak F(1), Fatmawati S(1)(3).
  As part of our project on exploring Indonesian medicinal plants for antidiabetic and anticancer agents, this study was conducted to investigate the total phenolic and flavonoid contents, and antioxidant, cytotoxic and antidiabetic properties of R. tomentosa leaf extracts. The antioxidant activity was tested using DPPH, ABTS, and FRAP methods. In vitro cytotoxic assay was performed against MCF-7, HeLa, A549, and B16 cancer cell lines. The in vitro antidiabetic testing was determined using α-glucosidase and α-amylase inhibitory evaluation, while STZ-induced diabetic rats were used for in vivo study. The highest values of total phenolic (191.97 ± 0.19 mg GAE g-1) and flavonoid (29.11 ± 0.05 mg QE g-1) contents were recorded in methanolic extract. This extract also showed the highest DPPH and ABTS activities with IC50 values of 7.79 ± 0.03 and 4.03 ± 0.02 μg mL-1, respectively, as well as the highest FRAP activity with a value of 64.05 ± 0.54 μM Fe2+ g-1. The methanol extract had cytotoxicity against MCF-7, HeLa, A549, and B16 cancer cell lines with IC50 values of 123.49 ± 0.79, 28.28 ± 0.17, 168.88 ± 1.14, and 42.44 ± 0.18 μg mL-1, respectively. In vitro antidiabetic evaluation indicated that the MeOH extract inhibited α-glucosidase and α-amylase with IC50 values of 45.73 ± 1.06 and 41.31 ± 1.12 μg mL-1, respectively. A dose of 400 mg kg-1 body weight of the MeOH extract reduced rats' blood glucose rate and serum blood glucose by 48.51% and 17.73%, respectively after 15 days of treatment. Taken together, these findings suggested that the methanolic extract of R. tomentosa leaves can be used as a potential source of antioxidant, cytotoxic, and antidiabetic agents.

Example Output1:
  a. Rhodomyrtus tomentosa = HSN
  b. Leaf = PH
  c. MCF-7 = CL
  d. HeLa = CL
  e. A549 = CL
  f. B16 = CL
  g. Phenolic = IG
  h. Flavonoid = IG
  i. Sesterpenoid = IG

- - -

Example Input2:
  Nano Uncaria gambir as Chemopreventive Agent Against Breast Cancer.
  Wardana AP(1), Aminah NS(1)(2), Kristanti AN(1)(2), Fahmi MZ(1), Zahrah HI(3), Widiyastuti W(4), Ajiz HA(4), Zubaidah U(5), Wiratama PA(6), Takaya Y(7).
  BACKGROUND: Breast cancer is one of the main causes of death in women. Uncaria gambir is an Indonesian herbal plant that can be used as an anti-cancer. However, herbal medicines have low bioavailability, which affects their bioactivity. Nanoencapsulation can increase bioavailability and stability of bioactive compounds in herbal medicines.
  PURPOSE: This recent finding tried to unravel anti-cancer and chemopreventive of U. gambir nano-encapsulated by Na-alginate.
  STUDY DESIGN: U. gambir bioactive compounds were isolated and characterized using UV-Vis spectrometer, FTIR, NMR and HR-MS. U. gambir extract was nanoencapsulated using Na-alginate. Anti-cancer effect was assessed by MTT assay towards T47D cell. Meanwhile, a chemopreventive analysis was carried out in breast cancer mice-induced benzo[α]pyrene. The healthy mice were divided into 8 groups comprising control and treatment.
  RESULTS: Elucidation of U. gambir ethyl acetate extract confirmed high catechin content, 89.34% (w/w). Successful nanoencapsulation of U. gambir (G-NPs) was indicated. The particle size of G-NPs was 78.40 ± 12.25 nm. Loading efficiency (LE) and loading amount (LA) of G-NPs were 97.56 ± 0.04% and 32.52 ± 0.01%, respectively. G-NPs had an EC50 value of 10.39 ± 3.50 µg/mL, which was more toxic than the EC50 value of extract towards the T47D cell line. Administration of 200 mg/kg BW G-NPs to mice induced by benzo[α]pyrene exhibited SOD and GSH levels of 13.69 ng/mL and 455.6 ng/mL. In addition, the lowest TNF-α level was 27.96 ng/mL. A dose of 100 mg/kg BW G-NPs could best increase CAT levels by 7.18 ng/mL. There was no damage or histological abnormalities found in histological analysis of the breast tissue in the group given 200 mg/kg BW G-NPs.

Example Output2:
  a. Breast cancer = DS
  b. Uncaria gambir = HSN
  c. T47D = CL
  d. Catechin = IG

- - -

Example Input3:
  Alpha-mangostin as an inhibitor of GSK3β in triple-negative breast cancer
  Abstract: Triple-negative breast cancer (TNBC) is a breast cancer subtype that does not express the estrogen receptor, the progesterone receptor, or the human epidermal growth factor receptor 2 and that is characterized by high invasiveness, high metastatic potential, and poor prognosis. TNBC lacks receptors and hence cannot be treated by using targeted therapies; as such, the therapeutic potential of Indonesian herbal plants against this disease is worth exploring. Herein, we explore the molecular docking and the molecular dynamics simulations of α-mangostin on glycogen synthase kinase 3β (GSK3β; PDB ID: 4ACC). Our findings reveal that α-mangostin has a weaker binding affinity to GSK3β than the native ligand (−8.22kcal/mol), while the latter binds to GSK3β with a stronger binding affinity of −8.92kcal/mol. According to the binding site analysis, the hydrogen bonds of the native ligand on Asp133 and Arg141, while α-mangostin only appeared to form a hydrogen bond on the enzyme’s Asp133. On the other hand, α-mangostin shares similar docking sites with the native ligand (namely, Ile62, Phe67, Val70, and Thr138), thus leading to the conclusion that the native ligand and α-mangostin might share a similar molecular mechanism. The molecular dynamics simulation by using the molecular mechanics Poisson-Boltzmann and surface area (MM-PBSA) calculations’ method shows that α-mangostin maintains a better affinity (with a value of ΔGTotal at −114.463kJ/mol) as compared with the native ligand (with a respective ΔGTotal value of −75.158kJ/mol). Our findings are suggestive of α-mangostin possessing a valuable potential as an anti-TNBC agent through GSK3β inhibition. Communicated by Ramaswamy H. Sarma.

Example Output3:
  a. Triple-negative breast cancer (TNBC) = DS
  b. α-mangostin = IG
  c. GSK3β = TG


Text:
{article_text}
"""

# 3. Fungsi ekstraksi entitas (per artikel)
def extract_entities(article_text: str) -> str | None:
    try:
        response = client.chat.completions.create(
            model="gpt-4o", #coba versi gpt-4 Turbo, gpt-5
            temperature=0,
            messages=[
                {"role": "system", "content": "You are a biomedical NER extractor."},
                {"role": "user", "content": prompt_template.format(article_text=article_text)}
            ]
        )
        content = response.choices[0].message.content.strip()

        # Antisipasi kalau model ngeyel dan ngasih ```csv ... ``` (kita bersihin)
        if content.startswith("```"):
            # buang ```...``` di awal/akhir
            content = re.sub(r"^```[a-zA-Z]*\n?", "", content)
            content = re.sub(r"\n?```$", "", content).strip()

        return content
    except Exception as e:
        print("❌ Error:", e)
        return None

# 4. Baca file teks
input_file = "Data Abstrak Paper.txt"
output_file = "gpt4o_(3)_Three-Shot.csv"

with open(input_file, "r", encoding="utf-8") as f:
    content = f.read()

# 5. Pisahkan artikel berdasarkan pemisah '---'
articles = [a.strip() for a in content.split("---") if a.strip()]
print(f"📄 Ditemukan {len(articles)} artikel untuk diproses.\n")

# 6. Loop ekstraksi untuk tiap artikel
all_dfs = []

for i, article_text in enumerate(articles, start=1):
    print(f"🔍 Memproses artikel {i}/{len(articles)}...")
    csv_snippet = extract_entities(article_text)

    if not csv_snippet:
        print(f"⚠️ Tidak ada output untuk artikel {i}, dilewati.")
        continue

    try:
        # Parse output TSV dari GPT jadi DataFrame, menggunakan '\t' sebagai pemisah
        df_article = pd.read_csv(StringIO(csv_snippet), sep='\t')

        # Tambahkan kolom article_id agar bisa dilacak ke artikel asal
        df_article.insert(0, "article_id", "A" + str(i))

        all_dfs.append(df_article)
    except Exception as e:
        print(f"⚠️ Gagal parse CSV untuk artikel {i}: **{e}**")
        print("Output mentah GPT:")
        print(csv_snippet)
        continue

    time.sleep(2) # jeda antar request untuk jaga-jaga rate limit

# 7. Gabungkan semua hasil dan simpan ke CSV
if all_dfs:
    df = pd.concat(all_dfs, ignore_index=True)
    df.to_csv(output_file, index=False, encoding="utf-8")
    print(f"\n✅ Ekstraksi selesai! Hasil disimpan di: **{output_file}**")
else:
    print("\n⚠️ Tidak ada data yang berhasil diekstraksi.")